Add task execution OQ tests

diff --git a/t/oq_tests/test b/t/oq_tests/test
--- a/t/oq_tests/test
+++ b/t/oq_tests/test
@@ -3,7 +3,6 @@ set -uo pipefail
 TESTS_SCRIPT_DIR=$(dirname "$(realpath "$0")")
 source "${TESTS_SCRIPT_DIR}/common.sh"
 
-# Check the base API
 if ! curl "${LOCAL_URL}" > /dev/null; then
     echo -e "\n${RED}FAILED TO GET BASE API${NC}"
     exit "${EXIT_CODE_FAILURE}"
@@ -19,3 +18,10 @@ if ! source "${TESTS_SCRIPT_DIR}/test_scripts/tasks_crud_test.sh"; then
     echo -e "\n${RED}TASKS CRUD TESTS FAILED${NC}"
     exit "${EXIT_CODE_FAILURE}"
 fi
+
+if ! source "${TESTS_SCRIPT_DIR}/test_scripts/tasks_exec_test.sh"; then
+    echo -e "\n${RED}TASKS CRUD TESTS FAILED${NC}"
+    exit "${EXIT_CODE_FAILURE}"
+fi
+
+echo -e "\n${GREEN}ALL TESTS SUCCESSFUL${NC}"
